# 应用名称
spring:
  application:
    name: camera
server:
  port: 8099



config:
  rtsp: /h.256
  path: C:\Users\Anonymous\Pictures\UbisoftConnect
####配置文件
camera:
  config:
#    -
#        name: 摄像头名称 用英文
#        host: 127.0.0.1
#        port: 544
#        user: 用户名
#        password: 密码
